service: serverless-react-app
app: ${env:APP_NAME}  # Placeholder for the name of the application
org: ${env:ORG_NAME}  # Placeholder for the name of the organization
useDotenv: true  # Enables loading environment variables from a .env file

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  # environment:
  #   BACKEND_API_BASE_ENDPOINT: ${self:custom.BACKEND_API_ENDPOINT}

plugins:
  - serverless-finch
  - serverless-build-client
  - serverless-dotenv-plugin

custom:
  # BACKEND_API_ENDPOINT: ${env:BACKEND_API_ENDPOINT}  # Placeholder for the name of the DynamoDB table
  hostS3BucketName: ${env:HOST_S3_BUCKET_NAME}
  buildClient:
    packager: npm
    command: run build
    cwd: my-app
    verbose: true  # Enables verbose output during the build process
  client:
    bucketName: ${self:custom.hostS3BucketName}  # Specifies the name of the host S3 bucket for the client
    distributionFolder: my-app/build  # Specifies the folder containing the built client files

